import iteratorsorts
import iterator
import linkedlist
import random

def main():
    #This main function tests out the iterators on python lists, linked lists, and double linked lists
    print('TESTING Selection Sort')
    for i in range(10):
        PList=[]
        LList = linkedlist.LinkedList()
        for j in range(20):
            b = random.randint(0,50)
            PList.append(b)
            LList.pushBack(b)            
        print('not sorted list:'+' ' + str(i+1))
        print(PList)
        print(LList)
        print()
        print('sorted list:'+' ' + str(i+1))
        iteratorsorts.selectionSort(iterator.PythonListFAIterator(PList,0))
        iteratorsorts.selectionSort(LList.getStartIter())        
        print(PList)
        print(LList)
    print()
    print('A Random 1-Element List')
    PList=[]
    LList = linkedlist.LinkedList()
    b = random.randint(0,50)
    PList.append(b)
    LList.pushBack(b)
    print('not sorted list:')
    print(PList)
    print(LList)
    print('sorted list')
    iteratorsorts.selectionSort(iterator.PythonListFAIterator(PList,0))
    iteratorsorts.selectionSort(LList.getStartIter())
    print(PList)
    print(LList)
    print()
    print('Empty List')
    PList=[]
    LList = linkedlist.LinkedList()
    print('not sorted list:')
    print(PList)
    print(LList)
    print('sorted list:')
    iteratorsorts.selectionSort(iterator.PythonListFAIterator(PList,0))
    iteratorsorts.selectionSort(LList.getStartIter())
    print(PList)
    print(LList)
    print()
    print()
    print('TESTING Insertion Sort')
    print()
    for i in range(10):
        PList=[]
        LList = linkedlist.DoubleLinkedList()
        for j in range(20):
            b = random.randint(0,50)
            PList.append(b)
            LList.pushBack(b)
        print('not sorted list:'+' ' + str(i+1))
        print(PList)
        print(LList)
        print('sorted list'+' ' + str(i+1))
        iteratorsorts.insertionSort(iterator.PythonListBAIterator(PList,0))
        iteratorsorts.insertionSort(LList.getStartIterator())
        print(PList)
        print(LList)
        print()
    print('A Random 1-element list')        
    PList=[]
    LList = linkedlist. DoubleLinkedList()
    b = random.randint(0,50)
    PList.append(b)
    LList.pushBack(b)
    print('not sorted list:')
    print(PList)
    print(LList)
    print('sorted list:')
    iteratorsorts.insertionSort(iterator.PythonListBAIterator(PList,0))
    iteratorsorts.insertionSort(LList.getStartIterator())
    print(PList)
    print(LList)
    print()
    print('Empty List')
    PList=[]
    LList =linkedlist. DoubleLinkedList()
    print('not sorted list:')
    print(PList)
    print(LList)
    print('sorted list')
    iteratorsorts.insertionSort(iterator.PythonListBAIterator(PList,0))
    iteratorsorts.insertionSort(LList.getStartIterator())
    print(PList)
    print(LList)
main()
